const CAPTCHA_SECRET = process.env.CAPTCHA_SECRET_KEY;
const CAPTCHA_SITE_KEY = process.env.CAPTCHA_SITE_KEY;
const CAPTCHA_ENABLED = process.env.CAPTCHA_ENABLED === "true";

export { CAPTCHA_SECRET, CAPTCHA_SITE_KEY, CAPTCHA_ENABLED };
